server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**
      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
        - Path=/hotels/**,/staffs/**
 #       - Path=/** you can use this to allow all urls
      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
        - Path=/ratings/**
           
  config:
    import: configserver:http://localhost:8084 
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8079/eureka

#okta configuration of api-gateway
okta:
  oauth2:
    issuer: https://dev-26569891.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa8xipb99wDnMnnM5d7
    client-secret: br8qqtyMDCbbEJHXnDTHzSBzejueqShrRIhTq6rk
    scopes: openid, profile, email, offline_access
    