server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/m-rating-service
    username: root
    password: root
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: RATING-SERVICE

  config:
    import: configserver:http://localhost:8084 
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8079/eureka

okta:
  oauth2:
    issuer: https://dev-26569891.okta.com/oauth2/default
    audience: api://default