server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/m-user-service
    username: root
    password: root
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
  application:
    name: USER-SERVICE
  config:
    import: configserver:http://localhost:8084 
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8079/eureka

#actuator configuration
management:
    health:
      circuitbreakers:
        enabled: true
    endpoints: 
       web:
         exposure:
          include: health

    endpoint:
      health:
        show-details: always

resilience4j:
  circuitbreaker:
    instances:
       ratingHotelBreaker:
         register-health-indicator: true
         event-consumer-buffer-size: 10
         failure-rate-threshold: 50
         minimum-number-of-calls: 5
         automatic-transition-from-open-to-half-open-enabled: true
         wait-duration-in-open-state: 6s
         permitted-number-of-calls-in-half-open-state: 3
         sliding-window-size: 10
         sliding-window-type: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s
        
  ratelimiter:
    instances:
       userRateLimiter:
         limit-refresh-period: 4s
         limit-for-period: 2
         timeout-duration: 2s
            